### ISSUE TITLE
Error when trying to run optimization into a directory that is not empty

### ISSUE THREAD

**Issue by clpetix** [mphowardlab/relentless#151]
If you try to run an optimization with a directory that is not empty the following error arises: 
`raise Error("Destination path '%s' already exists" % real_dst)`
The error arises because shutil move only allows moving files into an empty directory

**Comment by mphoward** [comment]
Thanks! Can you add to this test:

https://github.com/mphowardlab/relentless/blob/e441cd2d58c713e79237e421282349d8573e015e/tests/test_data.py#L149-L181

to reproduce the error before we fix?
