### ISSUE TITLE
Support freud 3.x

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/relentless#238]
freud released a major version 3, and currently relentless forces a check to major version 2. We should check if there are any breaking changes related to the parts we use:

https://freud.readthedocs.io/en/latest/gettingstarted/migration.html

and support both ASAP.

**Comment by clpetix** [comment]
I'll look through the changes and update to support version 3 ASAP. 

At a minimum we need to update: 
https://github.com/mphowardlab/relentless/blob/416348efb44320774e27b5f909e84ba5a05b947b/src/relentless/simulate/hoomd.py#L1567-L1568
